<?php

namespace App\Http\Controllers;

use App\Models\Datospersona;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Requests\DatospersonaRequest;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;
use PrintJS;

class DatospersonaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): View
    {
        $datospersonas = Datospersona::paginate();

        return view('datospersona.index', compact('datospersonas'))
            ->with('i', ($request->input('page', 1) - 1) * $datospersonas->perPage());
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $datospersona = new Datospersona();
        $profesiones = [
            'Abogacía',
            'Administradora De Empresas',
            'Agrimensor',
            'Arqueología',
            'Arquitecto Urbanista',
            'Auditoría Financiera',
            'Auxiliar En Enfermería',
            'Chef',
            'Cirujano Dentista',
            'Comunicador Audiovisual Con Mención En Radio Y Televisión',
            'Contador General',
            'Contaduría Financiera',
            'Contaduría Pública Con Autorización',
            'Contaduría Pública Y Auditoria Forense',
            'Doctor Anestesiólogo',
            'Doctor En Medicina',
            'Economista',
            'Educación Parvularia',
            'Educación Secundaria Comunitaria Productiva',
            'Educación Secundaria Comunitaria',
            'Educador Especial',
            'Especialista En Pediatría',
            'Fisioterapeuta',
            'Fonoaudiología',
            'Funcionario Policial',
            'Historia',
            'Ing. Acuicultor',
            'Ing. Aeroespacial',
            'Ing. Aeronáutica',
            'Ing. Agrícola',
            'Ing. Agroforestal',
            'Ing. Agroindustrial',
            'Ing. Agronómica',
            'Ing. Agropecuaria',
            'Ing. Ambiental',
            'Ing. Biomédica',
            'Ing. Civil',
            'Ing. Comercial',
            'Ing. De Alimentos',
            'Ing. De Recursos Hídricos',
            'Ing. De Sistemas',
            'Ing. Desarrollo Rural',
            'Ing. Electricista',
            'Ing. Eléctrico',
            'Ing. Electromecánica',
            'Ing. Electrónica',
            'Ing. Electrónico',
            'Ing. En Agronomía',
            'Ing. En Biología Marina',
            'Ing. En Desarrollo Rural Sostenible',
            'Ing. En Desarrollo Socioeconómico Y Ambiente',
            'Ing. En Eco Piscicultura',
            'Ing. En Ecología Y Medio Ambiente',
            'Ing. En Electromecánica',
            'Ing. En Fitotecnia',
            'Ing. En Gas Y Petróleo',
            'Ing. En Geodesia Y Topografía',
            'Ing. En Geodesia',
            'Ing. En Geografía',
            'Ing. En Irrigación',
            'Ing. En Materiales',
            'Ing. En Mecánica Agropecuaria',
            'Ing. En Medio Ambiente',
            'Ing. En Minas',
            'Ing. En Recursos Naturales',
            'Ing. En Redes Y Telecomunicaciones',
            'Ing. En Robótica',
            'Ing. En Sistemas Electrónicos',
            'Ing. En Sonido',
            'Ing. Financiera',
            'Ing. Forestal',
            'Ing. Geográfica Militar',
            'Ing. Geográfica',
            'Ing. Geológica',
            'Ing. Industrial',
            'Ing. Informática',
            'Ing. Informático',
            'Ing. Mecánica',
            'Ing. Mecánico',
            'Ing. Mecatrónica',
            'Ing. Médico Anestesista',
            'Ing. Metalúrgica',
            'Ing. Meteorológica',
            'Ing. Nuclear',
            'Ing. Petro Ambientalista',
            'Ing. Petrolera',
            'Ing. Petroquímica',
            'Ing. Química',
            'Ing. Químico Tecnólogo En El Carbono Y Sus Derivados',
            'Ing. Sanitario Y Ambiental',
            'Ing. Tecnologías De Información Y Seguridad',
            'Ing. Telecomunicaciones',
            'Ing. Zootécnico',
            'Lic. Auditoría Contaduría Pública',
            'Lic. Ciencias Militares Terrestres',
            'Lic. Ciencias Policiales',
            'Lic. Construcción Civil',
            'Lic. Diseño De Interiores E Inmobiliario',
            'Lic. Educación Técnica Tecnológica',
            'Lic. En Actividad Física',
            'Lic. En Administración De Empresas',
            'Lic. En Administración Educativa',
            'Lic. En Administración Financiera',
            'Lic. En Administración Y Gestión Publica',
            'Lic. En Agronomía',
            'Lic. En Antropología',
            'Lic. En Arquitectura Y Urbanismo',
            'Lic. En Arquitectura',
            'Lic. En Auditoría Y Contaduría Pública',
            'Lic. En Auditoria',
            'Lic. En Bio-Imagenología',
            'Lic. En Bioquímica Farmacéutica',
            'Lic. En Bioquímica Y Farmacia',
            'LIC. En Bioquímica',
            'Lic. En Bioquímico Farmacéutico',
            'Lic. En Ciencias De La Comunicación Social',
            'Lic. En Ciencias De La Educación Para El Desarrollo Humano',
            'Lic. En Ciencias De La Educación',
            'Lic. En Ciencias Jurídicas Y Políticas',
            'Lic. En Ciencias Jurídicas',
            'Lic. En Ciencias Naturales: Biología - Geografía',
            'Lic. En Ciencias Naturales: Física-Química',
            'Lic. En Ciencias Políticas',
            'Lic. En Ciencias Y Artes Militares Navales',
            'Lic. En Comercio Internacional',
            'Lic. En Comunicación Social',
            'Lic. En Construcción Civil',
            'Lic. En Contabilidad Y Finanzas',
            'Lic. En Contaduría Pública',
            'Lic. En Contaduría Y Auditoría De Sistemas',
            'Lic. En Derecho Ciencias Políticas Y Sociales',
            'Lic. En Derecho Y Ciencias Jurídicas',
            'Lic. En Derecho',
            'Lic. En Diseño Gráfico Y Comunicación Visual',
            'Lic. En Economía',
            'Lic. En Educación Escolar',
            'Lic. En Educación Especial',
            'Lic. En Educación Inicial En Familia Comunitaria',
            'Lic. En Educación Intercultural Bilingüe',
            'Lic. En Educación Intercultural Innovadora',
            'Lic. En Educación Técnica Y Tecnológica',
            'Lic. En Educación',
            'Lic. En Electricidad',
            'Lic. En Electro Mecánica',
            'Lic. En Enfermería Obstetríz',
            'Lic. En Enfermería Y Obstetricia',
            'Lic. En Enfermería',
            'Lic. En Estadística',
            'Lic. En Farmacia',
            'Lic. En Filosofía Y Letras',
            'Lic. En Física',
            'Lic. En Fisioterapia Y Kinesiología',
            'Lic. En Fonoaudiología',
            'Lic. En Geografía',
            'Lic. En Gestión Ambiental',
            'Lic. En Gestión Del Desarrollo Endógeno Y Agroecología',
            'Lic. En Idioma Inglés',
            'Lic. En Idiomas Inglés Y Francés',
            'Lic. En Informática',
            'Lic. En Ingeniería Agrónoma',
            'Lic. En Ingeniería Civil',
            'Lic. En Ingeniería De Sistemas',
            'Lic. En Ingeniería Electrónica',
            'Lic. En Ingeniería En Redes Y Telecomunicaciones',
            'Lic. En Ingeniería Geológica',
            'Lic. En Ingeniería Mecánica Automotriz',
            'Lic. En Laboratorio Clínico',
            'Lic. En Lingüística Aplicada A La Enseñanza De Lenguas',
            'Lic. En Lingüística E Idiomas',
            'Lic. En Marketing Y Publicidad',
            'Lic. En Matemática',
            'Lic. En Mecánica Industrial',
            'Lic. En Medicina Veterinaria Y Zootecnia',
            'Lic. En Medicina',
            'Lic. En Negocios Internacionales',
            'Lic. En Nutrición Y Dietética',
            'Lic. En Odontología',
            'Lic. En Orden Y Seguridad',
            'Lic. En Pedagogía Social',
            'Lic. En Pedagogía',
            'Lic. En Psicología',
            'Lic. En Psicopedagogía',
            'Lic. En Química Farmacéutica',
            'Lic. En Química Industrial',
            'Lic. En Relaciones Internacionales',
            'Lic. En Teología',
            'Lic. En Trabajo Social',
            'Lic. En Turismo Y Hotelería',
            'Lic. En Turismo',
            'Lic. Farmacia Y Bioquímica',
            'Lic. Ingeniería Química Industrial',
            'Lic. Laboratorista',
            'Lic. Literatura',
            'Lic. Medicina Forense',
            'Lic. Planificación Territorial',
            'Lic. Psicomotricidad',
            'Lic. Técnica Tecnológica Comunitaria',
            'Lic. Técnica Tecnológica General',
            'Licenciada En Trabajo Social',
            'Licenciatura En Sociología',
            'Maestra De Educación Alternativa Educación De Personas Jóvenes Y Adultas',
            'Maestra De Educación Primaria Comunitaria Vocacional',
            'Maestra De Física Y Química',
            'Maestra De Matemática',
            'Maestra De Técnica Tecnológica General',
            'Maestro De Cosmovisiones, Filosofía Y Psicología',
            'Mecánico',
            'Medicina Familiar',
            'Medico Anestesiólogo',
            'Médico Cirujano',
            'Médico Especialista En Radiología',
            'Médico General',
            'Médico Ginecólogo Obstetra',
            'Médico Integral Comunitario',
            'Médico Internista',
            'Médico Reumatólogo',
            'Médico Veterinario',
            'Nutricionista',
            'Oficial De Policía',
            'Optometría',
            'Profesor',
            'Químico Farmacéutico',
            'Relaciones Internacionales',
            'Sociólogo',
            'Técnico Electrónico',
            'Técnico En Bibliotecología',
            'Técnico Medio En Auxiliar De Enfermería',
            'Técnico Medio En Enfermería',
            'Técnico Medio En Gastronomía',
            'Técnico Superior Electrónica Y Telecomunicaciones',
            'Técnico Superior En Electricidad Industrial',
            'Técnico Superior En Electromecánica',
            'Técnico Superior En Mantenimiento De Equipo Pesado',
            'Técnico Superior En Química Industrial',
            'Técnico Superior En Secretariado Ejecutivo',
            'Técnico Superior En Topografía',
            'Técnico Superior Mecánica Automotriz',
            'Trabajadora Social',

        ];
        return view('datospersona.create', compact('datospersona', 'profesiones'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(DatospersonaRequest $request): RedirectResponse
    {
        Datospersona::create($request->validated());

        return Redirect::route('datospersonas.index')
            ->with('success', 'Registrado correctamente.');
    }

    /**
     * Display the specified resource.
     */
    public function show($id): View
    {
        $datospersona = Datospersona::find($id);
        $profesiones = [
            'Abogacía',
            'Administradora De Empresas',
            'Agrimensor',
            'Arqueología',
            'Arquitecto Urbanista',
            'Auditoría Financiera',
            'Auxiliar En Enfermería',
            'Chef',
            'Cirujano Dentista',
            'Comunicador Audiovisual Con Mención En Radio Y Televisión',
            'Contador General',
            'Contaduría Financiera',
            'Contaduría Pública Con Autorización',
            'Contaduría Pública Y Auditoria Forense',
            'Doctor Anestesiólogo',
            'Doctor En Medicina',
            'Economista',
            'Educación Parvularia',
            'Educación Secundaria Comunitaria Productiva',
            'Educación Secundaria Comunitaria',
            'Educador Especial',
            'Especialista En Pediatría',
            'Fisioterapeuta',
            'Fonoaudiología',
            'Funcionario Policial',
            'Historia',
            'Ing. Acuicultor',
            'Ing. Aeroespacial',
            'Ing. Aeronáutica',
            'Ing. Agrícola',
            'Ing. Agroforestal',
            'Ing. Agroindustrial',
            'Ing. Agronómica',
            'Ing. Agropecuaria',
            'Ing. Ambiental',
            'Ing. Biomédica',
            'Ing. Civil',
            'Ing. Comercial',
            'Ing. De Alimentos',
            'Ing. De Recursos Hídricos',
            'Ing. De Sistemas',
            'Ing. Desarrollo Rural',
            'Ing. Electricista',
            'Ing. Eléctrico',
            'Ing. Electromecánica',
            'Ing. Electrónica',
            'Ing. Electrónico',
            'Ing. En Agronomía',
            'Ing. En Biología Marina',
            'Ing. En Desarrollo Rural Sostenible',
            'Ing. En Desarrollo Socioeconómico Y Ambiente',
            'Ing. En Eco Piscicultura',
            'Ing. En Ecología Y Medio Ambiente',
            'Ing. En Electromecánica',
            'Ing. En Fitotecnia',
            'Ing. En Gas Y Petróleo',
            'Ing. En Geodesia Y Topografía',
            'Ing. En Geodesia',
            'Ing. En Geografía',
            'Ing. En Irrigación',
            'Ing. En Materiales',
            'Ing. En Mecánica Agropecuaria',
            'Ing. En Medio Ambiente',
            'Ing. En Minas',
            'Ing. En Recursos Naturales',
            'Ing. En Redes Y Telecomunicaciones',
            'Ing. En Robótica',
            'Ing. En Sistemas Electrónicos',
            'Ing. En Sonido',
            'Ing. Financiera',
            'Ing. Forestal',
            'Ing. Geográfica Militar',
            'Ing. Geográfica',
            'Ing. Geológica',
            'Ing. Industrial',
            'Ing. Informática',
            'Ing. Informático',
            'Ing. Mecánica',
            'Ing. Mecánico',
            'Ing. Mecatrónica',
            'Ing. Médico Anestesista',
            'Ing. Metalúrgica',
            'Ing. Meteorológica',
            'Ing. Nuclear',
            'Ing. Petro Ambientalista',
            'Ing. Petrolera',
            'Ing. Petroquímica',
            'Ing. Química',
            'Ing. Químico Tecnólogo En El Carbono Y Sus Derivados',
            'Ing. Sanitario Y Ambiental',
            'Ing. Tecnologías De Información Y Seguridad',
            'Ing. Telecomunicaciones',
            'Ing. Zootécnico',
            'Lic. Auditoría Contaduría Pública',
            'Lic. Ciencias Militares Terrestres',
            'Lic. Ciencias Policiales',
            'Lic. Construcción Civil',
            'Lic. Diseño De Interiores E Inmobiliario',
            'Lic. Educación Técnica Tecnológica',
            'Lic. En Actividad Física',
            'Lic. En Administración De Empresas',
            'Lic. En Administración Educativa',
            'Lic. En Administración Financiera',
            'Lic. En Administración Y Gestión Publica',
            'Lic. En Agronomía',
            'Lic. En Antropología',
            'Lic. En Arquitectura Y Urbanismo',
            'Lic. En Arquitectura',
            'Lic. En Auditoría Y Contaduría Pública',
            'Lic. En Auditoria',
            'Lic. En Bio-Imagenología',
            'Lic. En Bioquímica Farmacéutica',
            'Lic. En Bioquímica Y Farmacia',
            'LIC. En Bioquímica',
            'Lic. En Bioquímico Farmacéutico',
            'Lic. En Ciencias De La Comunicación Social',
            'Lic. En Ciencias De La Educación Para El Desarrollo Humano',
            'Lic. En Ciencias De La Educación',
            'Lic. En Ciencias Jurídicas Y Políticas',
            'Lic. En Ciencias Jurídicas',
            'Lic. En Ciencias Naturales: Biología - Geografía',
            'Lic. En Ciencias Naturales: Física-Química',
            'Lic. En Ciencias Políticas',
            'Lic. En Ciencias Y Artes Militares Navales',
            'Lic. En Comercio Internacional',
            'Lic. En Comunicación Social',
            'Lic. En Construcción Civil',
            'Lic. En Contabilidad Y Finanzas',
            'Lic. En Contaduría Pública',
            'Lic. En Contaduría Y Auditoría De Sistemas',
            'Lic. En Derecho Ciencias Políticas Y Sociales',
            'Lic. En Derecho Y Ciencias Jurídicas',
            'Lic. En Derecho',
            'Lic. En Diseño Gráfico Y Comunicación Visual',
            'Lic. En Economía',
            'Lic. En Educación Escolar',
            'Lic. En Educación Especial',
            'Lic. En Educación Inicial En Familia Comunitaria',
            'Lic. En Educación Intercultural Bilingüe',
            'Lic. En Educación Intercultural Innovadora',
            'Lic. En Educación Técnica Y Tecnológica',
            'Lic. En Educación',
            'Lic. En Electricidad',
            'Lic. En Electro Mecánica',
            'Lic. En Enfermería Obstetríz',
            'Lic. En Enfermería Y Obstetricia',
            'Lic. En Enfermería',
            'Lic. En Estadística',
            'Lic. En Farmacia',
            'Lic. En Filosofía Y Letras',
            'Lic. En Física',
            'Lic. En Fisioterapia Y Kinesiología',
            'Lic. En Fonoaudiología',
            'Lic. En Geografía',
            'Lic. En Gestión Ambiental',
            'Lic. En Gestión Del Desarrollo Endógeno Y Agroecología',
            'Lic. En Idioma Inglés',
            'Lic. En Idiomas Inglés Y Francés',
            'Lic. En Informática',
            'Lic. En Ingeniería Agrónoma',
            'Lic. En Ingeniería Civil',
            'Lic. En Ingeniería De Sistemas',
            'Lic. En Ingeniería Electrónica',
            'Lic. En Ingeniería En Redes Y Telecomunicaciones',
            'Lic. En Ingeniería Geológica',
            'Lic. En Ingeniería Mecánica Automotriz',
            'Lic. En Laboratorio Clínico',
            'Lic. En Lingüística Aplicada A La Enseñanza De Lenguas',
            'Lic. En Lingüística E Idiomas',
            'Lic. En Marketing Y Publicidad',
            'Lic. En Matemática',
            'Lic. En Mecánica Industrial',
            'Lic. En Medicina Veterinaria Y Zootecnia',
            'Lic. En Medicina',
            'Lic. En Negocios Internacionales',
            'Lic. En Nutrición Y Dietética',
            'Lic. En Odontología',
            'Lic. En Orden Y Seguridad',
            'Lic. En Pedagogía Social',
            'Lic. En Pedagogía',
            'Lic. En Psicología',
            'Lic. En Psicopedagogía',
            'Lic. En Química Farmacéutica',
            'Lic. En Química Industrial',
            'Lic. En Relaciones Internacionales',
            'Lic. En Teología',
            'Lic. En Trabajo Social',
            'Lic. En Turismo Y Hotelería',
            'Lic. En Turismo',
            'Lic. Farmacia Y Bioquímica',
            'Lic. Ingeniería Química Industrial',
            'Lic. Laboratorista',
            'Lic. Literatura',
            'Lic. Medicina Forense',
            'Lic. Planificación Territorial',
            'Lic. Psicomotricidad',
            'Lic. Técnica Tecnológica Comunitaria',
            'Lic. Técnica Tecnológica General',
            'Licenciada En Trabajo Social',
            'Licenciatura En Sociología',
            'Maestra De Educación Alternativa Educación De Personas Jóvenes Y Adultas',
            'Maestra De Educación Primaria Comunitaria Vocacional',
            'Maestra De Física Y Química',
            'Maestra De Matemática',
            'Maestra De Técnica Tecnológica General',
            'Maestro De Cosmovisiones, Filosofía Y Psicología',
            'Mecánico',
            'Medicina Familiar',
            'Medico Anestesiólogo',
            'Médico Cirujano',
            'Médico Especialista En Radiología',
            'Médico General',
            'Médico Ginecólogo Obstetra',
            'Médico Integral Comunitario',
            'Médico Internista',
            'Médico Reumatólogo',
            'Médico Veterinario',
            'Nutricionista',
            'Oficial De Policía',
            'Optometría',
            'Profesor',
            'Químico Farmacéutico',
            'Relaciones Internacionales',
            'Sociólogo',
            'Técnico Electrónico',
            'Técnico En Bibliotecología',
            'Técnico Medio En Auxiliar De Enfermería',
            'Técnico Medio En Enfermería',
            'Técnico Medio En Gastronomía',
            'Técnico Superior Electrónica Y Telecomunicaciones',
            'Técnico Superior En Electricidad Industrial',
            'Técnico Superior En Electromecánica',
            'Técnico Superior En Mantenimiento De Equipo Pesado',
            'Técnico Superior En Química Industrial',
            'Técnico Superior En Secretariado Ejecutivo',
            'Técnico Superior En Topografía',
            'Técnico Superior Mecánica Automotriz',
            'Trabajadora Social',

        ];
        return view('datospersona.show', compact('datospersona', 'profesiones'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id): View
    {
        $datospersona = Datospersona::find($id);
        $profesiones = [
            'Abogacía',
            'Administradora De Empresas',
            'Agrimensor',
            'Arqueología',
            'Arquitecto Urbanista',
            'Auditoría Financiera',
            'Auxiliar En Enfermería',
            'Chef',
            'Cirujano Dentista',
            'Comunicador Audiovisual Con Mención En Radio Y Televisión',
            'Contador General',
            'Contaduría Financiera',
            'Contaduría Pública Con Autorización',
            'Contaduría Pública Y Auditoria Forense',
            'Doctor Anestesiólogo',
            'Doctor En Medicina',
            'Economista',
            'Educación Parvularia',
            'Educación Secundaria Comunitaria Productiva',
            'Educación Secundaria Comunitaria',
            'Educador Especial',
            'Especialista En Pediatría',
            'Fisioterapeuta',
            'Fonoaudiología',
            'Funcionario Policial',
            'Historia',
            'Ing. Acuicultor',
            'Ing. Aeroespacial',
            'Ing. Aeronáutica',
            'Ing. Agrícola',
            'Ing. Agroforestal',
            'Ing. Agroindustrial',
            'Ing. Agronómica',
            'Ing. Agropecuaria',
            'Ing. Ambiental',
            'Ing. Biomédica',
            'Ing. Civil',
            'Ing. Comercial',
            'Ing. De Alimentos',
            'Ing. De Recursos Hídricos',
            'Ing. De Sistemas',
            'Ing. Desarrollo Rural',
            'Ing. Electricista',
            'Ing. Eléctrico',
            'Ing. Electromecánica',
            'Ing. Electrónica',
            'Ing. Electrónico',
            'Ing. En Agronomía',
            'Ing. En Biología Marina',
            'Ing. En Desarrollo Rural Sostenible',
            'Ing. En Desarrollo Socioeconómico Y Ambiente',
            'Ing. En Eco Piscicultura',
            'Ing. En Ecología Y Medio Ambiente',
            'Ing. En Electromecánica',
            'Ing. En Fitotecnia',
            'Ing. En Gas Y Petróleo',
            'Ing. En Geodesia Y Topografía',
            'Ing. En Geodesia',
            'Ing. En Geografía',
            'Ing. En Irrigación',
            'Ing. En Materiales',
            'Ing. En Mecánica Agropecuaria',
            'Ing. En Medio Ambiente',
            'Ing. En Minas',
            'Ing. En Recursos Naturales',
            'Ing. En Redes Y Telecomunicaciones',
            'Ing. En Robótica',
            'Ing. En Sistemas Electrónicos',
            'Ing. En Sonido',
            'Ing. Financiera',
            'Ing. Forestal',
            'Ing. Geográfica Militar',
            'Ing. Geográfica',
            'Ing. Geológica',
            'Ing. Industrial',
            'Ing. Informática',
            'Ing. Informático',
            'Ing. Mecánica',
            'Ing. Mecánico',
            'Ing. Mecatrónica',
            'Ing. Médico Anestesista',
            'Ing. Metalúrgica',
            'Ing. Meteorológica',
            'Ing. Nuclear',
            'Ing. Petro Ambientalista',
            'Ing. Petrolera',
            'Ing. Petroquímica',
            'Ing. Química',
            'Ing. Químico Tecnólogo En El Carbono Y Sus Derivados',
            'Ing. Sanitario Y Ambiental',
            'Ing. Tecnologías De Información Y Seguridad',
            'Ing. Telecomunicaciones',
            'Ing. Zootécnico',
            'Lic. Auditoría Contaduría Pública',
            'Lic. Ciencias Militares Terrestres',
            'Lic. Ciencias Policiales',
            'Lic. Construcción Civil',
            'Lic. Diseño De Interiores E Inmobiliario',
            'Lic. Educación Técnica Tecnológica',
            'Lic. En Actividad Física',
            'Lic. En Administración De Empresas',
            'Lic. En Administración Educativa',
            'Lic. En Administración Financiera',
            'Lic. En Administración Y Gestión Publica',
            'Lic. En Agronomía',
            'Lic. En Antropología',
            'Lic. En Arquitectura Y Urbanismo',
            'Lic. En Arquitectura',
            'Lic. En Auditoría Y Contaduría Pública',
            'Lic. En Auditoria',
            'Lic. En Bio-Imagenología',
            'Lic. En Bioquímica Farmacéutica',
            'Lic. En Bioquímica Y Farmacia',
            'LIC. En Bioquímica',
            'Lic. En Bioquímico Farmacéutico',
            'Lic. En Ciencias De La Comunicación Social',
            'Lic. En Ciencias De La Educación Para El Desarrollo Humano',
            'Lic. En Ciencias De La Educación',
            'Lic. En Ciencias Jurídicas Y Políticas',
            'Lic. En Ciencias Jurídicas',
            'Lic. En Ciencias Naturales: Biología - Geografía',
            'Lic. En Ciencias Naturales: Física-Química',
            'Lic. En Ciencias Políticas',
            'Lic. En Ciencias Y Artes Militares Navales',
            'Lic. En Comercio Internacional',
            'Lic. En Comunicación Social',
            'Lic. En Construcción Civil',
            'Lic. En Contabilidad Y Finanzas',
            'Lic. En Contaduría Pública',
            'Lic. En Contaduría Y Auditoría De Sistemas',
            'Lic. En Derecho Ciencias Políticas Y Sociales',
            'Lic. En Derecho Y Ciencias Jurídicas',
            'Lic. En Derecho',
            'Lic. En Diseño Gráfico Y Comunicación Visual',
            'Lic. En Economía',
            'Lic. En Educación Escolar',
            'Lic. En Educación Especial',
            'Lic. En Educación Inicial En Familia Comunitaria',
            'Lic. En Educación Intercultural Bilingüe',
            'Lic. En Educación Intercultural Innovadora',
            'Lic. En Educación Técnica Y Tecnológica',
            'Lic. En Educación',
            'Lic. En Electricidad',
            'Lic. En Electro Mecánica',
            'Lic. En Enfermería Obstetríz',
            'Lic. En Enfermería Y Obstetricia',
            'Lic. En Enfermería',
            'Lic. En Estadística',
            'Lic. En Farmacia',
            'Lic. En Filosofía Y Letras',
            'Lic. En Física',
            'Lic. En Fisioterapia Y Kinesiología',
            'Lic. En Fonoaudiología',
            'Lic. En Geografía',
            'Lic. En Gestión Ambiental',
            'Lic. En Gestión Del Desarrollo Endógeno Y Agroecología',
            'Lic. En Idioma Inglés',
            'Lic. En Idiomas Inglés Y Francés',
            'Lic. En Informática',
            'Lic. En Ingeniería Agrónoma',
            'Lic. En Ingeniería Civil',
            'Lic. En Ingeniería De Sistemas',
            'Lic. En Ingeniería Electrónica',
            'Lic. En Ingeniería En Redes Y Telecomunicaciones',
            'Lic. En Ingeniería Geológica',
            'Lic. En Ingeniería Mecánica Automotriz',
            'Lic. En Laboratorio Clínico',
            'Lic. En Lingüística Aplicada A La Enseñanza De Lenguas',
            'Lic. En Lingüística E Idiomas',
            'Lic. En Marketing Y Publicidad',
            'Lic. En Matemática',
            'Lic. En Mecánica Industrial',
            'Lic. En Medicina Veterinaria Y Zootecnia',
            'Lic. En Medicina',
            'Lic. En Negocios Internacionales',
            'Lic. En Nutrición Y Dietética',
            'Lic. En Odontología',
            'Lic. En Orden Y Seguridad',
            'Lic. En Pedagogía Social',
            'Lic. En Pedagogía',
            'Lic. En Psicología',
            'Lic. En Psicopedagogía',
            'Lic. En Química Farmacéutica',
            'Lic. En Química Industrial',
            'Lic. En Relaciones Internacionales',
            'Lic. En Teología',
            'Lic. En Trabajo Social',
            'Lic. En Turismo Y Hotelería',
            'Lic. En Turismo',
            'Lic. Farmacia Y Bioquímica',
            'Lic. Ingeniería Química Industrial',
            'Lic. Laboratorista',
            'Lic. Literatura',
            'Lic. Medicina Forense',
            'Lic. Planificación Territorial',
            'Lic. Psicomotricidad',
            'Lic. Técnica Tecnológica Comunitaria',
            'Lic. Técnica Tecnológica General',
            'Licenciada En Trabajo Social',
            'Licenciatura En Sociología',
            'Maestra De Educación Alternativa Educación De Personas Jóvenes Y Adultas',
            'Maestra De Educación Primaria Comunitaria Vocacional',
            'Maestra De Física Y Química',
            'Maestra De Matemática',
            'Maestra De Técnica Tecnológica General',
            'Maestro De Cosmovisiones, Filosofía Y Psicología',
            'Mecánico',
            'Medicina Familiar',
            'Medico Anestesiólogo',
            'Médico Cirujano',
            'Médico Especialista En Radiología',
            'Médico General',
            'Médico Ginecólogo Obstetra',
            'Médico Integral Comunitario',
            'Médico Internista',
            'Médico Reumatólogo',
            'Médico Veterinario',
            'Nutricionista',
            'Oficial De Policía',
            'Optometría',
            'Profesor',
            'Químico Farmacéutico',
            'Relaciones Internacionales',
            'Sociólogo',
            'Técnico Electrónico',
            'Técnico En Bibliotecología',
            'Técnico Medio En Auxiliar De Enfermería',
            'Técnico Medio En Enfermería',
            'Técnico Medio En Gastronomía',
            'Técnico Superior Electrónica Y Telecomunicaciones',
            'Técnico Superior En Electricidad Industrial',
            'Técnico Superior En Electromecánica',
            'Técnico Superior En Mantenimiento De Equipo Pesado',
            'Técnico Superior En Química Industrial',
            'Técnico Superior En Secretariado Ejecutivo',
            'Técnico Superior En Topografía',
            'Técnico Superior Mecánica Automotriz',
            'Trabajadora Social',

        ];
        return view('datospersona.edit', compact('datospersona', 'profesiones'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(DatospersonaRequest $request, Datospersona $datospersona): RedirectResponse
    {
        $datospersona->update($request->validated());

        return Redirect::route('datospersonas.index')
            ->with('success', 'Modificado correctamente');
    }

    public function destroy($id): RedirectResponse
    {
        Datospersona::find($id)->delete();

        return Redirect::route('datospersonas.index')
            ->with('success', 'Eliminado correctamente');
    }
}
